# Generated by Django 5.1.15 on 2026-07-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=64)),
                ('recipient_mailbox', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('offer', 'offer'), ('answer', 'answer'), ('candidate', 'candidate'), ('ringing', 'ringing'), ('hangup', 'hangup'), ('busy', 'busy')], max_length=12)),
                ('ciphertext', models.BinaryField()),
                ('seq', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['seq', 'created_at'],
                'indexes': [models.Index(fields=['recipient_mailbox', 'delivered'], name='calling_cal_recipie_9934b6_idx'), models.Index(fields=['call_id', 'seq'], name='calling_cal_call_id_ebf9fa_idx')],
            },
        ),
    ]
