# Generated by Django 5.1.15 on 2026-07-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsverify', '0002_registerednumber_registrationtoken_msisdn_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mailbox_id', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
