# Generated by Django 5.1.15 on 2026-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsverify', '0003_phonedirectoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='purpose',
            field=models.CharField(default='signup', max_length=16),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='purpose',
            field=models.CharField(default='signup', max_length=16),
        ),
    ]
