# Generated by Django 5.1.15 on 2026-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed25519_pub', models.CharField(db_index=True, max_length=64)),
                ('doc_type', models.CharField(max_length=20)),
                ('doc_number_hash', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ed25519_pub', 'doc_type', 'doc_number_hash')},
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('birth_certificate', 'birth_certificate'), ('nid', 'nid')], max_length=20)),
                ('doc_number_hash', models.CharField(db_index=True, max_length=64)),
                ('fields_hash', models.JSONField(default=dict)),
                ('enc_fields', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('doc_type', 'doc_number_hash')},
            },
        ),
    ]
