# Generated by Django 5.1.15 on 2026-07-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ed25519_pub', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_key', models.CharField(db_index=True, max_length=128)),
                ('window', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('bucket_key', 'window')},
            },
        ),
    ]
