# Generated by Django 5.1.15 on 2026-07-29 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('mailbox_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ed25519_pub', models.CharField(db_index=True, max_length=64, unique=True)),
                ('x25519_pub', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_bucket', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PreKeyBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_prekey', models.CharField(max_length=64)),
                ('signed_prekey_sig', models.CharField(max_length=128)),
                ('one_time_prekeys', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prekeys', to='directory.identity')),
            ],
        ),
    ]
