# Generated by Django 5.1.15 on 2026-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identity',
            name='fcm_token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
