# Generated by Django 5.1.15 on 2026-08-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_identity_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('encrypted_bundle', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
