# Generated by Django 5.1.15 on 2026-07-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64)),
                ('ciphertext', models.BinaryField()),
                ('recipient_mailbox', models.UUIDField(db_index=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('ttl_expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlobFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(db_index=True, max_length=64)),
                ('idx', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('recipient_mailbox', models.UUIDField(db_index=True)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('size_bucket', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=160)),
                ('uploaded', models.BooleanField(default=False)),
                ('ttl_expires_at', models.DateTimeField(db_index=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_mailbox', 'delivered'], name='sync_blobfr_recipie_6e2ac5_idx')],
                'unique_together': {('transfer_id', 'idx')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('recipient_mailbox', models.UUIDField(db_index=True)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('size_bucket', models.PositiveIntegerField()),
                ('ciphertext', models.BinaryField()),
                ('ttl_expires_at', models.DateTimeField(db_index=True)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_mailbox', 'delivered'], name='sync_event_recipie_31e09c_idx'), models.Index(fields=['priority', 'created_at'], name='sync_event_priorit_69cb1c_idx')],
            },
        ),
    ]
