# Generated by Django 5.1.15 on 2026-07-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordDelta',
            fields=[
                ('delta_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('geohash', models.CharField(db_index=True, max_length=12)),
                ('ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['geohash', 'created_at'], name='coordinatio_geohash_8be70a_idx')],
            },
        ),
    ]
